# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

 platform :ios, '9.0'

target 'SwitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#网络请求
    pod 'Alamofire', '~> 4.7.3'
#json解析
#pod 'SwiftJSONKit', '~> 0.1.0'
#图片加载
    pod 'Kingfisher', '~> 4.8.1'

  # Pods for SwitDemo

  target 'SwitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
