# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

 platform :ios, '10.0'

target 'SwitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    #网络请求
    pod 'Alamofire', '~> 4.7.3'
    #json解析
#    pod 'SwiftyJSON', '~> 4.1.0' 不好用
pod 'HandyJSON', '~> 5.0.0'
    #图片加载
    pod 'Kingfisher', '~> 4.8.1'
    #自动布局约束
    pod 'SnapKit', '~> 5.0.1'
    #是一个可以帮助我们简化异步编程的框架,KVO，异步操作 和 流 全部被统一成抽象序列
    #pod 'RxSwift', '~> 5.0'
    #pod 'RxCocoa', '~> 5.0'

  # Pods for SwitDemo
  #无限轮播
  pod 'FSPagerView', '~> 0.8.3'

  target 'SwitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
